### ISSUE TITLE
add pip2 to Enum for pip_provider

### ISSUE THREAD

**Issue by jippolito-nasuni** [voxpupuli/puppet-python#567]
For the pip_provider (and version) we have a need to support pip2.  Currently we need to symbolic link pip2 to pip to ensure that it meets the requirements for this module.  https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/

https://forge.puppet.com/puppet/python/reference#pip_provider-1
https://forge.puppet.com/puppet/python/reference#version-1

**Comment by igalic** [comment]
python 2 is EOL https://www.python.org/dev/peps/pep-0373/ since April 2020

can we please let it rest in peace.?

**Comment by jippolito-nasuni** [comment]
As much as I'd love to, there are a ton of legacy systems out there on python2 that won't be upgraded ever or not in the near future.

**Comment by igalic** [comment]
being unpaid volunteers, it's hard enough for us to support all the variations on different operating systems of the supported versions of software that our modules manage.

That python 2.7 is EOL is *not* a surprise.
The first time this was announced and then pushed back was 2014.

If you need to support legacy software, you can probably do that with an older version of this module, but i think it does a great disservice to the entire FLOSS community (especially the ones of us who do this for free) to focus energy on keeping this python2 zombie alive, rather than upgrading to python3
